language: generic
branches:
  only:
    - master
matrix:
  include:
  - os: linux
    dist: bionic
    sudo: required
    compiler: gcc
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
        packages:
          - g++-8
          - "python3"
          - "python3-pip"
    env:
      - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
  - os: osx
    compiler: clang
    osx_image: xcode11

before_install:
  - |
    python3 -m pip install pip --upgrade --user
    python3 -m pip install numpy --upgrade --user
    git clone https://github.com/Dekken/maiken --depth 10 -b master maiken
    [[ "${TRAVIS_OS_NAME}" == "osx" ]] && make bsd -C maiken CXX="clang++"
    [[ "${TRAVIS_OS_NAME}" == "linux" ]] && eval "${MATRIX_EVAL}"
    [[ "${TRAVIS_OS_NAME}" == "linux" ]] && make nix -C maiken CXX="$CXX"
    mv maiken/mkn .

script:
  - |
    export MKN_LIB_LINK_LIB="1" export KLOG="3" CC CXX
    ./mkn build -tOa "-fPIC -std=c++17" -d
    ./mkn build -tOa "-fPIC -std=c++17" -p test run -l "-pthread -ldl"
